#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TokenKind {
	Ampersand,
	AndKeyword,
	AnyKeyword,
	AscKeyword,
	Asterisk,
	BangEqual,
	BoolKeyword,
	BreakKeyword,
	ByKeyword,
	Colon,
	Comma,
	ConstKeyword,
	ContinueKeyword,
	CountKeyword,
	CreateKeyword,
	Dash,
	DateKeyword,
	DateLiteral,
	DecKeyword,
	DecimalLiteral,
	DescKeyword,
	Dot,
	ElseKeyword,
	EndOfFile,
	EnumKeyword,
	Equal,
	EqualEqual,
	FalseKeyword,
	FindKeyword,
	FirstKeyword,
	FnKeyword,
	ForKeyword,
	ForwardSlash,
	GreaterThan,
	GreaterThanOrEqual,
	Identifier,
	IfKeyword,
	InKeyword,
	IntKeyword,
	InterpolatedStringEnd,
	InterpolatedStringMiddle,
	InterpolatedStringStart,
	IntegerLiteral,
	LastKeyword,
	LeftBrace,
	LeftBracket,
	LeftParenthesis,
	LessThan,
	LessThanOrEqual,
	MinusEqual,
	MultiplyEqual,
	MutKeyword,
	NewKeyword,
	NotKeyword,
	NullKeyword,
	ObjKeyword,
	OrKeyword,
	OrderKeyword,
	Percent,
	PercentEqual,
	Pipe,
	Plus,
	PlusEqual,
	PubKeyword,
	Question,
	RecKeyword,
	ReturnKeyword,
	RightBrace,
	RightBracket,
	RightParenthesis,
	Semicolon,
	SlashEqual,
	StringLiteral,
	TextKeyword,
	TimeKeyword,
	TimeTzKeyword,
	TimestampKeyword,
	TimestampTzKeyword,
	TrueKeyword,
	VarKeyword,
	VoidKeyword,
	WhereKeyword,
	WhileKeyword,
	WithKeyword,
	XorKeyword,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Token {
	pub end: usize,
	pub kind: TokenKind,
	pub lexeme: String,
	pub start: usize,
}
