#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TokenKind {
	AndKeyword,
	Asterisk,
	BangEqual,
	BoolKeyword,
	BreakKeyword,
	Colon,
	Comma,
	ConstKeyword,
	ContinueKeyword,
	Dash,
	DecKeyword,
	DecimalLiteral,
	ElseKeyword,
	EndOfFile,
	Equal,
	EqualEqual,
	FalseKeyword,
	FnKeyword,
	ForwardSlash,
	GreaterThan,
	GreaterThanOrEqual,
	Identifier,
	IfKeyword,
	IntKeyword,
	InterpolatedStringEnd,
	InterpolatedStringMiddle,
	InterpolatedStringStart,
	IntegerLiteral,
	LeftBrace,
	LeftBracket,
	LeftParenthesis,
	LessThan,
	LessThanOrEqual,
	MinusEqual,
	MultiplyEqual,
	NotKeyword,
	OrKeyword,
	Percent,
	PercentEqual,
	Plus,
	PlusEqual,
	ReturnKeyword,
	RightBrace,
	RightBracket,
	RightParenthesis,
	Semicolon,
	SlashEqual,
	StringLiteral,
	TextKeyword,
	TrueKeyword,
	VarKeyword,
	VoidKeyword,
	WhileKeyword,
	XorKeyword,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Token {
	pub end: usize,
	pub kind: TokenKind,
	pub lexeme: String,
	pub start: usize,
}
